services:
  postgres-default:
    container_name: milions-postgres-default
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: milions_db
    ports:
      - 5433:5432
    volumes:
      - ./psqldata01:/var/lib/postgresql/data
    networks:
      - milions-network

networks:
  milions-network:
    driver: bridge
