services:
  postgres-default:
    container_name: postgres-default
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5432:5432
    networks:
      - milions-network

networks:
  milions-network:
    driver: bridge
